"""initial_entities

Revision ID: 740d6789f75d
Revises: 
Create Date: 2018-02-20 03:42:41.749648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '740d6789f75d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_of_crawling', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('able_to_vote', sa.Boolean(), nullable=False),
    sa.Column('last_vote_datetime', sa.DateTime(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('crawl_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formid', sa.String(length=2), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('xpath', sa.String(length=80), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('click_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['crawl_spot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawl_form')
    op.drop_table('credential')
    op.drop_table('crawl_spot')
    op.drop_table('server')
    # ### end Alembic commands ###
