"""init

Revision ID: d1735752f86c
Revises: 
Create Date: 2018-04-10 17:10:03.825349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1735752f86c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credential')
    op.drop_table('server')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('server_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('last_vote_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='server_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('credential',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('able_to_vote', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_vote_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('server_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], name='credential_server_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='credential_pkey')
    )
    # ### end Alembic commands ###
